### ISSUE TITLE
Issue connecting to mgo in Docker container

### ISSUE THREAD

**Issue by jbelmont** [go-mgo/mgo#460]
```yml
version: '3'
services:
  db:
    image: mongo:3.4.5
    ports:
      - "27017:27017"
    volumes:
      - ./:/data/db
  redis:
    image: redis:3.2.9-alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOCKER: "true"
    volumes:
      - .:/var/www/app/:rw
      - /var/www/app/node_modules
    ports:
      - "3000:8081"
    restart: always
  test:
    image: mhart/alpine-node:8.0.0
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    environment:
      NODE_ENV: testing
    command:
      /bin/sh -c "./node_modules/.bin/ava test/unit/*.js"
  backend:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: go run main.go
    volumes:
      - .:/var/www/app/:rw
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: "127.0.0.1:27017"
      REDIS_URL: "redis"
    restart: always
    links:
      - db
      - redis
```

```yml
FROM golang:1.8.3-alpine

LABEL maintainer "marcelbelmont@gmail.com"

# Set Environment variables
ENV appDir /var/www/app

RUN apk add --no-cache make gcc g++ python bash go git mercurial subversion openssh-client ca-certificates

# Set the work directory
RUN mkdir -p ${appDir}
WORKDIR ${appDir}

RUN go get gopkg.in/mgo.v2
RUN go get github.com/keimoon/gore
RUN go get github.com/gorilla/mux
RUN go get github.com/gorilla/handlers
RUN go get github.com/jbelmont/docker-workshop/routes
RUN go get github.com/jbelmont/docker-workshop/handlers
RUN go get github.com/jbelmont/docker-workshop/model
RUN go get github.com/jbelmont/docker-workshop/redis
```

```yml
FROM mhart/alpine-node:8.0.0

LABEL maintainer "marcelbelmont@gmail.com"

# Set Environment variables
ENV appDir /var/www/app

RUN apk add --no-cache make gcc g++ python bash bzr git subversion openssh-client ca-certificates

# Set the work directory
RUN mkdir -p ${appDir}
WORKDIR ${appDir}

COPY . ${appDir}
COPY package.json ${appDir}/package.json

# Install npm dependencies and install ava globally
RUN npm install

# Add main node execution command
CMD ["npm", "run", "dev:docker"]
```

```go
package model

import (
	"log"

	mgo "gopkg.in/mgo.v2"
)

// DBName is name of the database and CName is the name of document collection
const (
	DBName = "docker"
	CName  = "users"
)

var session *mgo.Session

// CreateDBSession creates mgo session
func CreateDBSession() {
	var err error
	Host := []string{
		"127.0.0.1:27017",
		// replica set addrs...
	}
	session, err := mgo.DialWithInfo(&mgo.DialInfo{
		Addrs: Host,
		// Username: Username,
		// Password: Password,
		// Database: Database,
		// DialServer: func(addr *mgo.ServerAddr) (net.Conn, error) {
		// 	return tls.Dial("tcp", addr.String(), &tls.Config{})
		// },
	})
	defer session.Close()
	if err != nil {
		log.Fatal("Cannot Dial Mongo: ", err)
	}
	session.SetMode(mgo.Monotonic, true)
	collection := InitDB()
	CreateInitDocument(collection)
}

// GetSession will create a session if doesn't exist else will return existing session
func GetSession() *mgo.Session {
	if session == nil {
		CreateDBSession()
	}
	return session
}

// InitDB is to be used in main.go to initialize database
func InitDB() *mgo.Collection {
	c := NewContext()
	return c.DBCollection()
}

// CreateInitDocument initializes collection with 50 users
func CreateInitDocument(m *mgo.Collection) {
	models := GetModels()
	for _, model := range models {
		m.Insert(model)
	}
}
```

I am running the following command `docker-compose build` and then `docker-compose up frontend backend db redis` and mgo keeps panicking with the url
